### ISSUE TITLE
size = 100000, 503 Server Error: Service Temporarily Unavailable

### ISSUE THREAD

**Issue by foximulder** [Storj/downstream-farmer#30]
I have some troubles, if I use the optional size parameter with 100000 :(
Gerald

![unbenannt1](https://cloud.githubusercontent.com/assets/8937420/5903242/d1468d9e-a580-11e4-81dd-93ab3adba957.PNG)

**Comment by EmergentBehavior** [comment]
I think there may be an issue with rate limiting. Can you try again in 5-10 minutes to see?

**Comment by foximulder** [comment]
ok

**Comment by super3** [comment]
@foximulder Force refresh `-f` and use the 100-byte size. You are above the limit for size in this round of testing, and the server will rate limit you. We will bring this up to 100 GB in the next test, but the nodes we are testing now don't support more than 60k.
