### ISSUE TITLE
v0.1.6 windows build file?  

### ISSUE THREAD

**Issue by foximulder** [Storj/downstream-farmer#31]
Please, can anybody upload the v0.1.6 windows build file?  
Thanx

**Comment by super3** [comment]
Why do you need the build file? v0.1.6 is still being tested and bug fixed on our local cluster.

**Comment by foximulder** [comment]
sorry, I thought it would be ready for testing.
Is it now released?

**Comment by super3** [comment]
We will send a message via the mailing list when its time to upgrade.
