### ISSUE TITLE
load_cert_crl_file

### ISSUE THREAD

**Issue by lucvanbraekel** [Storj/downstream-farmer#32]
This latest version, where the ca-cert is no longer in the data directory, I get this runtime error on Ubuntu 14.04:

`Unexpected error: [Errno 185090050] _ssl.c:344: error:0B084002:x509 certificate routines:X509_load_cert_crl_file:system lib`

**Comment by lucvanbraekel** [comment]
Solved. An old version was present in /usr/local/bin/downstream.  Was this automatically installed by a previous version, and if yes, why wasn't it overwritten?

**Comment by super3** [comment]
Strange. May just be a Linux from source issue. Let us know if you encounter this again.

**Comment by lucvanbraekel** [comment]
So, there was a previous version of "downstream" in my /usr/local/bin.  With this new version, I first tried to install it with "pip install ..." but then repeated it with "sudo pip install...".  Could that be the reason why the previous version in /usr/local/bin was not overwritten?

Now this issue is solved, but I'm getting another error: "Malformed response from server".

**Comment by EmergentBehavior** [comment]
`sudo pip install` installs it to your system and `pip install` may/may not install it locally. Generally you should isolate your downstream installation in a virtual environment to ensure everything works well. I'd save your identities file, uninstall everything, then follow the directions [here](https://github.com/Storj/downstream-farmer/wiki/Test-Group-A-FAQ#ubuntu). Use the 'from source' version.

Ultimately it'll be much easier to install but hey this is part of the fun of being an early tester :)
