### ISSUE TITLE
I Don't Have money to buy SJCX Please Help Me...... :(

### ISSUE THREAD

**Issue by dansus021** [Storj/downstream-farmer#33]
Please Help me guys I Really dont have much bitcoin to buy your coin Please Help Me

16ifVAL4n4UCVQ7SZQythUrWofNKdvGqDK

**Comment by EmergentBehavior** [comment]
Sorry, but GitHub issues aren't appropriate for requests of this type. This area is for development concerns related to downstream-farmer.

**Comment by dansus021** [comment]
Okay Fine I'Am soory dude  :D
But can you make tutorial in video please
