### ISSUE TITLE
Please Help Me About The Tutorial

### ISSUE THREAD

**Issue by dansus021** [Storj/downstream-farmer#34]
Okay Fine I'Am soory dude :D From my fisrt issue
But can you make tutorial in video please

**Comment by dansus021** [comment]
Please Help Me I really don't understand

**Comment by dansus021** [comment]
What is node.example.org  <-- Please :(

**Comment by nameone** [comment]
The current release for Group A is this one v0.1.5: https://github.com/Storj/downstream-farmer/releases/tag/v0.1.5. Higher releases are for internal testing only for the moment.

**Comment by dansus021** [comment]
I'm just confused on the number 6 :( Please Gift me video tutorial

**Comment by dansus021** [comment]
whether I should buy coins scjx first

**Comment by dansus021** [comment]
Answer me dude :(

**Comment by nameone** [comment]
Help me understand first, have you participated in the crowdsale we held back in July?

**Comment by dansus021** [comment]
No :(

**Comment by nameone** [comment]
So you will only be able to participate in Test Group C which is some time away. Until then you won't be able to test downstream-farmer. We will make announcements before Test Group C starts. For more information please check: http://storj.io/earlyaccess and http://storj.io/faq. Thank you for the interest.

**Comment by dansus021** [comment]
Okay Thankyou for your answer

**Comment by nameone** [comment]
You are welcome. And make sure you register for our newsletter on http://storj.io so we can keep you updated with the latest news and updates ;)

**Comment by dansus021** [comment]
i am already subscribed Storj Newsletter :+1:  I will Be wait

**Comment by EmergentBehavior** [comment]
GitHub issues are only for software-related concerns.
