### ISSUE TITLE
Limit the upload/download speed

### ISSUE THREAD

**Issue by alphaonex86** [Storj/downstream-farmer#35]
Hello,
can you add option to limit the upload/download?
Cheers,

**Comment by super3** [comment]
We will at some point. If we don't add it immediately, I would just recommend you use something like http://www.netlimiter.com/

**Comment by alphaonex86** [comment]
I known how do it on my OS ;) (Linux), but limit into application is more easy.

**Comment by super3** [comment]
Its pretty high on the priority list just can't guarantee it in the very
first version.

Shawn
